package Client_Master;

import javax.swing.*;

public class LoginCliente extends javax.swing.JFrame {

    /**
     * Creates new form LoginCliente
     */
    public LoginCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        botonAdminLogin = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        labelContra = new javax.swing.JLabel();
        botonUserLogin = new javax.swing.JButton();
        labelRegistrarse = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JButton();
        contraField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 51, 51));
        labelLogin.setText("LOGIN");
        labelLogin.setAlignmentY(0.0F);
        labelLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelError.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 51, 51));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelError.setText("");

        labelUserName.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        labelUserName.setText("Introduzca su user name");

        labelAdmin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        labelAdmin.setText("Eres un administrador?");

        botonAdminLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        botonAdminLogin.setText("Login");
        botonAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminLoginActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelContra.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        labelContra.setText("Introduzca su contraseña");

        botonUserLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        botonUserLogin.setText("Login");
        botonUserLogin.setToolTipText("");
        botonUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUserLoginActionPerformed(evt);
            }
        });

        labelRegistrarse.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        labelRegistrarse.setText("No tienes cuenta aun?");

        botonRegistrarse.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        contraField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 186, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(labelLogin)
                                                                                .addGap(89, 89, 89))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(labelUserName)
                                                                                .addGap(55, 55, 55))
                                                                        .addComponent(labelContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(botonUserLogin)
                                                                                .addGap(98, 98, 98))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(labelRegistrarse)
                                                                                .addGap(63, 63, 63))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(botonRegistrarse)
                                                                                .addGap(75, 75, 75))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(contraField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(30, 30, 30)))
                                                                .addGap(158, 158, 158))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelAdmin, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(botonAdminLogin)
                                                                                .addGap(38, 38, 38)))
                                                                .addGap(27, 27, 27))))
                                        .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAdminLogin)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(labelUserName))
                                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelContra)
                                .addGap(18, 18, 18)
                                .addComponent(contraField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonUserLogin)
                                .addGap(18, 18, 18)
                                .addComponent(labelRegistrarse)
                                .addGap(18, 18, 18)
                                .addComponent(botonRegistrarse)
                                .addGap(41, 41, 41)
                                .addComponent(labelError)
                                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void botonAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {
        LoginAdmin admin = new LoginAdmin();
        admin.setVisible(true);
        admin.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void botonUserLoginActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Sockets.out.println("validarUser");
            Sockets.out.println(usernameField.getText());
            Sockets.out.println(contraField.getText());
            String response = Sockets.in.readLine();
            if (response.equals("true")) {
                ClientApp client = new ClientApp();
                client.setVisible(true);
                client.setLocationRelativeTo(null);
                this.setVisible(false);
            } else {
                labelError.setText("El usuario o contraseña son incorrectos");
            }
        }
        catch (Exception e) {
            System.out.println("Server no conectado");
        }
    }

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        Register admin = new Register();
        admin.setVisible(true);
        admin.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void contraFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonAdminLogin;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JButton botonUserLogin;
    private javax.swing.JPasswordField contraField;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelRegistrarse;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JTextField usernameField;
    // End of variables declaration
}