package Client_Master;

import java.io.IOException;

public class MasterApp extends javax.swing.JFrame {

    /**
     * Creates new form MasterApp
     */
    public MasterApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        labelBienvenida = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonAddAdmin = new javax.swing.JButton();
        botonAgregarPlatillos = new javax.swing.JButton();
        botonPedidosActivos = new javax.swing.JButton();
        botonElimEditPlatillos = new javax.swing.JButton();
        botonEditUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBienvenida.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        labelBienvenida.setForeground(new java.awt.Color(255, 51, 51));
        labelBienvenida.setText("Administracion");
        labelBienvenida.setAlignmentY(0.0F);
        labelBienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        botonSalir.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setToolTipText("");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonAddAdmin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        botonAddAdmin.setText("Agregar administrador");
        botonAddAdmin.setToolTipText("");
        botonAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddAdminActionPerformed(evt);
            }
        });

        botonAgregarPlatillos.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        botonAgregarPlatillos.setText("Agregar platillos");
        botonAgregarPlatillos.setToolTipText("");
        botonAgregarPlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlatillosActionPerformed(evt);
            }
        });

        botonPedidosActivos.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        botonPedidosActivos.setText("Pedidos en curso");
        botonPedidosActivos.setToolTipText("");
        botonPedidosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    botonPedidosActivosActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        botonElimEditPlatillos.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        botonElimEditPlatillos.setText("Eliminar y editar platillos");
        botonElimEditPlatillos.setToolTipText("");
        botonElimEditPlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElimEditPlatillosActionPerformed(evt);
            }
        });

        botonEditUser.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        botonEditUser.setText("Editar clientes");
        botonEditUser.setToolTipText("");
        botonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBienvenida)
                                .addGap(175, 175, 175))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonSalir)
                                                .addGap(340, 340, 340))
                                        .addComponent(botonAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(botonAgregarPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(botonPedidosActivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(botonEditUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botonElimEditPlatillos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(botonSalir)
                                .addGap(11, 11, 11)
                                .addComponent(labelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(botonAddAdmin)
                                .addGap(34, 34, 34)
                                .addComponent(botonAgregarPlatillos)
                                .addGap(29, 29, 29)
                                .addComponent(botonPedidosActivos)
                                .addGap(35, 35, 35)
                                .addComponent(botonElimEditPlatillos)
                                .addGap(36, 36, 36)
                                .addComponent(botonEditUser)
                                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {
        LoginCliente login = new LoginCliente();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void botonAddAdminActionPerformed(java.awt.event.ActionEvent evt) {
        AddAdmin add = new AddAdmin();
        add.setVisible(true);
        add.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void botonAgregarPlatillosActionPerformed(java.awt.event.ActionEvent evt) {
        AddPlatillo addPlatillo = new AddPlatillo();
        addPlatillo.setVisible(true);
        addPlatillo.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void botonPedidosActivosActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        PedidosActivos pedidos = new PedidosActivos();
        pedidos.setVisible(true);
        pedidos.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void botonElimEditPlatillosActionPerformed(java.awt.event.ActionEvent evt) {
        ElimEditPlatillos elimEdit = new ElimEditPlatillos();
        elimEdit.setVisible(true);
        elimEdit.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void botonEditUserActionPerformed(java.awt.event.ActionEvent evt) {
        EditUser elimEdit = new EditUser();
        elimEdit.setVisible(true);
        elimEdit.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonAddAdmin;
    private javax.swing.JButton botonAgregarPlatillos;
    private javax.swing.JButton botonEditUser;
    private javax.swing.JButton botonElimEditPlatillos;
    private javax.swing.JButton botonPedidosActivos;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel labelBienvenida;
    // End of variables declaration
}